### ISSUE TITLE
Aromaticity detection problems in thermo?

### ISSUE THREAD

**Issue by rwest** [GreenGroup/RMG-Py#106]
Compare the thermo for the kekulized benzene
http://rmg.mit.edu/database/thermo/molecule/1%20C%200%20%7B2,S%7D%20%7B6,D%7D%0D%0A2%20C%200%20%7B1,S%7D%20%7B3,D%7D%0D%0A3%20C%200%20%7B2,D%7D%20%7B4,S%7D%0D%0A4%20C%200%20%7B3,S%7D%20%7B5,D%7D%0D%0A5%20C%200%20%7B4,D%7D%20%7B6,S%7D%0D%0A6%20C%200%20%7B1,D%7D%20%7B5,S%7D%0D%0A

with the aromatic version
http://rmg.mit.edu/database/thermo/molecule/1%20C%200%20%7B2,B%7D%20%7B6,B%7D%0D%0A2%20C%200%20%7B1,B%7D%20%7B3,B%7D%0D%0A3%20C%200%20%7B2,B%7D%20%7B4,B%7D%0D%0A4%20C%200%20%7B3,B%7D%20%7B5,B%7D%0D%0A5%20C%200%20%7B4,B%7D%20%7B6,B%7D%0D%0A6%20C%200%20%7B1,B%7D%20%7B5,B%7D%0D%0A

Not sure how widespread this is, or what the consequences are for building models.
(Does it depend on how we define our reactants?)

What if we make an aromatic thing via reactions from non-aromatic things - do we detect it?

**Comment by connie** [comment]
Currently closed via https://github.com/GreenGroup/RMG-Py/pull/322
