### ISSUE TITLE
Some aromatic species fail isomorphism check

### ISSUE THREAD

**Issue by connie** [GreenGroup/RMG-Py#291]
This following two versions of indene are not considered isomorphisms of each other in the current version of RMG-Py:

Adjlist 1

    1  C 0 0 {2,S} {4,S} {10,S} {11,S}
    2  C 0 0 {1,S} {3,D} {5,S}
    3  C 0 0 {2,D} {6,S} {7,S}
    4  C 0 0 {1,S} {6,D} {12,S}
    5  C 0 0 {2,S} {8,D} {13,S}
    6  C 0 0 {3,S} {4,D} {17,S}
    7  C 0 0 {3,S} {9,D} {16,S}
    8  C 0 0 {5,D} {9,S} {14,S}
    9  C 0 0 {7,D} {8,S} {15,S}
    10 H 0 0 {1,S}
    11 H 0 0 {1,S}
    12 H 0 0 {4,S}
    13 H 0 0 {5,S}
    14 H 0 0 {8,S}
    15 H 0 0 {9,S}
    16 H 0 0 {7,S}
    17 H 0 0 {6,S}

Adjlist 2

    1  C 0 0 {2,S} {4,S} {10,S} {11,S}
    2  C 0 0 {1,S} {3,S} {5,D}
    3  C 0 0 {2,S} {6,S} {7,D}
    4  C 0 0 {1,S} {6,D} {12,S}
    5  C 0 0 {2,D} {8,S} {13,S}
    6  C 0 0 {3,S} {4,D} {17,S}
    7  C 0 0 {3,D} {9,S} {16,S}
    8  C 0 0 {5,S} {9,D} {14,S}
    9  C 0 0 {7,S} {8,D} {15,S}
    10 H 0 0 {1,S}
    11 H 0 0 {1,S}
    12 H 0 0 {4,S}
    13 H 0 0 {5,S}
    14 H 0 0 {8,S}
    15 H 0 0 {9,S}
    16 H 0 0 {7,S}
    17 H 0 0 {6,S}

**Comment by connie** [comment]
Yes and no.  It is now fixed such that a species object generated from either adjacency list and then running the generateResonanceIsomers() command will give isormorphic species.  However, molecule objects themselves will not give true when you run the isIsormophic() command because the graphs are distinctly different.

I think almost everywhere, including where chemkin files are loaded and where reactions are generated, we do use the generateResonanceIsomers() function, so it should be ok.  But we just have to be careful when writing new code.

**Comment by rwest** [comment]
I think that is correct / expected behaviour. Isomorphism is GRAPH isomorphism, and knows nothing about chemistry.  Checking if two species are the same chemical species, requires checking the graph isomorphism of each resonance isomer. Thanks for sorting this. I wonder if we can extend it beyond what RMG-Java could do, eg. allow N and 5-membered rings, etc. But that's another issue.
