### ISSUE TITLE
Error when Visualizing RMG-Generated Mechanism with Duplicate Chebyshev Reactions

### ISSUE THREAD

**Issue by arosen93** [GreenGroup/RMG-Py#328]
When attempting to use the "visualize Chemkin file" tool on the RMG website with an RMG-generated Chemkin file, I receive the following error message: "Unexpected kinetics type <type 'rmgpy.kinetics.chebyshev.Chebyshev'> for duplicate reaction HO2(8) + S(1109) <=> H(6) + S(8294).

The mechanism generated by RMG produced two identical reactions with separate Chebyshev representations (shown below), but the visualization tool is unable to work when this occurs. Deleting one of the duplicates "resolves" the issue.

Duplicate Chebyshev reactions causing visualization error: 

HO2(8)+S(1109)(+M)=H(6)+S(8294)(+M)                 1.000e+00 0.000     0.000    
    TCHEB/ 290.000   3500.000 /
    PCHEB/ 0.020     98.692   /
    CHEB/ 6 4/
    CHEB/ -3.793e+00   -1.667e-02   -1.111e-02   -5.798e-03  /
    CHEB/ 1.410e+01    1.481e-02    9.843e-03    5.104e-03   /
    CHEB/ 3.734e-01    3.013e-03    2.031e-03    1.079e-03   /
    CHEB/ -3.561e-02   -1.316e-03   -8.558e-04   -4.267e-04  /
    CHEB/ -7.699e-02   5.111e-04    3.314e-04    1.644e-04   /
    CHEB/ -4.972e-02   -2.314e-04   -1.549e-04   -8.129e-05  /
DUPLICATE

HO2(8)+S(1109)(+M)=H(6)+S(8294)(+M)                 1.000e+00 0.000     0.000    
    TCHEB/ 290.000   3500.000 /
    PCHEB/ 0.020     98.692   /
    CHEB/ 6 4/
    CHEB/ -4.382e+00   -1.819e-02   -1.212e-02   -6.318e-03  /
    CHEB/ 1.290e+01    9.194e-03    6.121e-03    3.185e-03   /
    CHEB/ 6.950e-01    1.194e-02    7.912e-03    4.083e-03   /
    CHEB/ 1.224e-01    -2.362e-03   -1.529e-03   -7.570e-04  /
    CHEB/ -1.891e-02   -1.039e-03   -6.688e-04   -3.269e-04  /
    CHEB/ 8.272e-04    3.133e-04    1.894e-04    8.122e-05   /
DUPLICATE

**Comment by connie** [comment]
This commit https://github.com/GreenGroup/RMG-Py/commit/65a720917d6b8e403d7b2042e1c7d17c8631cf7c hopes to address this.
