### ISSUE TITLE
RMG generates a edge model with numerous missing species

### ISSUE THREAD

**Issue by enochd** [GreenGroup/RMG-Py#338]
Discovered this while trying to visualize a edge mechanism. Many species are missing from the list. Here is one example of an input file that can be used to reproduce the problem:
```python
# Data sources
database(
    thermoLibraries = ['primaryThermoLibrary', 'DME'],
    reactionLibraries = [('DME',False)],
    seedMechanisms = [],
    kineticsDepositories = ['training'], 
    kineticsFamilies = 'default',
    kineticsEstimator = 'rate rules',
)

# Constraints on generated species
generatedSpeciesConstraints(
    allowed=['reaction libraries'],
    maximumRadicalElectrons = 2,
)

# List of species
species(
    label='DME',
    reactive=True,
    structure=SMILES("COC"),
)
species(
    label='C3H8',
    reactive=True,
    structure=SMILES("CCC"),
)
species(
    label='O2',
    reactive=True,
    structure=SMILES("O=O"),
)

species(
    label='N2',
    reactive=False,
    structure=InChI("InChI=1/N2/c1-2"),
)

# Reaction systems
simpleReactor(
    temperature=(850,'K'),
    pressure=(10.0,'bar'),
    initialMoleFractions={
        "DME": 1,
        "C3H8": 1,
        "O2": 8,
        "N2": 30.1,
    },
    terminationConversion={
        'DME': 0.2,
    },
    terminationTime=(1e0,'s'),
)
simpleReactor(
    temperature=(850,'K'),
    pressure=(50.0,'bar'),
    initialMoleFractions={
        "DME": .1,
        "C3H8": .1,
        "O2": 8,
        "N2": 30.1,
    },
    terminationConversion={
        'DME': 0.2,
    },
    terminationTime=(1e-1,'s'), #since there are two termination criteria rmg halt whenever the first one is reached
)
simpleReactor(
    temperature=(650,'K'),
    pressure=(50.0,'bar'),
    initialMoleFractions={
        "DME": .1,
        "C3H8": .1,
        "O2": 8,
        "N2": 30.1,
    },
    terminationConversion={
        'DME': 0.2,
    },
    terminationTime=(1e0,'s'),
)
simulator(
    atol=1e-16,
    rtol=1e-8,
)

model(
    toleranceKeepInEdge=0.0,
    toleranceMoveToCore=0.5,
    toleranceInterruptSimulation=0.9,
    maximumEdgeSpecies=1000
)

options(
    units='si',
    saveRestartPeriod=(1,'hour'),
    drawMolecules=False,
    generatePlots=False,
    saveEdgeSpecies=True,
)
```

**Comment by connie** [comment]
What do you mean by edge species are missing? What specifically are you
looking for?

On Thu, Feb 12, 2015 at 5:13 PM, Enoch Dames <notifications@github.com>
wrote:

> Discovered this while trying to visualize a edge mechanism. Many species
> are missing from the list. Here is one example of an input file that can be
> used to reproduce the problem:
>
> # Data sources
> database(
>     thermoLibraries = ['primaryThermoLibrary', 'DME'],
>     reactionLibraries = [('DME',False)],
>     seedMechanisms = [],
>     kineticsDepositories = ['training'],
>     kineticsFamilies = 'default',
>     kineticsEstimator = 'rate rules',
> )
>
> # Constraints on generated species
> generatedSpeciesConstraints(
>     allowed=['reaction libraries'],
>     maximumRadicalElectrons = 2,
> )
>
> # List of species
> species(
>     label='DME',
>     reactive=True,
>     structure=SMILES("COC"),
> )
> species(
>     label='C3H8',
>     reactive=True,
>     structure=SMILES("CCC"),
> )
> species(
>     label='O2',
>     reactive=True,
>     structure=SMILES("O=O"),
> )
>
> species(
>     label='N2',
>     reactive=False,
>     structure=InChI("InChI=1/N2/c1-2"),
> )
>
> # Reaction systems
> simpleReactor(
>     temperature=(850,'K'),
>     pressure=(10.0,'bar'),
>     initialMoleFractions={
>         "DME": 1,
>         "C3H8": 1,
>         "O2": 8,
>         "N2": 30.1,
>     },
>     terminationConversion={
>         'DME': 0.2,
>     },
>     terminationTime=(1e0,'s'),
> )
> simpleReactor(
>     temperature=(850,'K'),
>     pressure=(50.0,'bar'),
>     initialMoleFractions={
>         "DME": .1,
>         "C3H8": .1,
>         "O2": 8,
>         "N2": 30.1,
>     },
>     terminationConversion={
>         'DME': 0.2,
>     },
>     terminationTime=(1e-1,'s'), #since there are two termination criteria rmg halt whenever the first one is reached
> )
> simpleReactor(
>     temperature=(650,'K'),
>     pressure=(50.0,'bar'),
>     initialMoleFractions={
>         "DME": .1,
>         "C3H8": .1,
>         "O2": 8,
>         "N2": 30.1,
>     },
>     terminationConversion={
>         'DME': 0.2,
>     },
>     terminationTime=(1e0,'s'),
> )
> simulator(
>     atol=1e-16,
>     rtol=1e-8,
> )
>
> model(
>     toleranceKeepInEdge=0.0,
>     toleranceMoveToCore=0.5,
>     toleranceInterruptSimulation=0.9,
>     maximumEdgeSpecies=1000
> )
>
> options(
>     units='si',
>     saveRestartPeriod=(1,'hour'),
>     drawMolecules=False,
>     generatePlots=False,
>     saveEdgeSpecies=True,
> )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GreenGroup/RMG-Py/issues/338>.
>



-- 
Connie Gao
connieg@mit.edu || homepage <http://www.conniegao.com> || 978-500-5197
Chemical Engineering PhD Candidate
Massachusetts Institute of Technology

**Comment by enochd** [comment]
Some species corresponding to those in the edge mechanism are not printed out in the SPECIES section of the chemkin files, and it looks like in output_edge.html as well. For example, the H radical is one!

**Comment by enochd** [comment]
I should further clarify with 'Some species corresponding to reactions of the edge mechanism.."

**Comment by connie** [comment]
I see.  Basically the species are undeclared at the top and do not supply the thermo even though they are included in the edge reactions, making the chemkin file not actually functional.

I think the fix would be to include all the core species in the declarations.

**Comment by connie** [comment]
Would it be more beneficial to save a chemkin edge file that contains ONLY edge reactions, or includes core+edge reactions?  Somehow it feels to me now that the latter option may be better.

**Comment by rwest** [comment]
What is this edge file (typically) used for?

**Comment by connie** [comment]
Right now I think just to see what reactions are too slow to be entering the core for troubleshooting.  Also to see if RMG is actually missing some reaction path.

**Comment by enochd** [comment]
Edge+core is certainly preferred. The edge mechanism is good for seeing what reactions are too slow to enter the core but also plausibly important for low temperature chemistry, where slow reactions can dictate and define autoignition. Does this make sense?

**Comment by connie** [comment]
Modified to now save core+edge into chemkin_edge.inp on official/master: https://github.com/GreenGroup/RMG-Py/commit/2636154ff3fcfca4a5f836d0b0cf9bfba4dee3d9
