### ISSUE TITLE
Updates to PyDAS

### ISSUE THREAD

**Issue by rwest** [GreenGroup/RMG-Py#339]
@jwallen has updated (or is updating) PyDAS with a change that will require:
 * [ ] updates to our installation instructions
 * [ ] updates to how we import PyDAS modules
 * [ ] the latter preferably with a check that at least gives a nice "please upgrade PyDAS" error message, or perhaps better yet a warning and backwards-compatible work-around.

See https://github.com/jwallen/PyDAS/pull/12
Although the https://github.com/GreenGroup/PyDAS fork seems to be divorced form Josh's I suggest we merge his recent changes.

**Comment by connie** [comment]
I have some changes of my own on https://github.com/connie/PyDAS/commits/master allowing PyDAS to receive additional arguments so that the functional calls to both DASPK and DASSL can be the same and used interchangeably.  If we are going to make the update we should probably do it altogether.

**Comment by rwest** [comment]
Agree to making the changes all at once for RMG.
I suggest you rebase your changes onto jwallen/PyDAS then submit a pull request to it to keep them in sync.

**Comment by jwallen** [comment]
I grabbed @connie's changes - I was thinking of making those changes too, so it was nice to find them already done! I'll probably merge it into my master soon, and then leave it to you guys to update GreenGroup/PyDAS so I don't interrupt any RMG work.

As for backwards compatibility, making `from pydas import DASSL` still work would be easy, but I don't think there's any way to make `from pydas cimport DASSL` work, or even to influence the (compile-time) error message. Best bet is probably to update the documentation with the specific error you get when PyDAS hasn't been updated and instructions on how to fix.
