### ISSUE TITLE
Reaction isomorphism returns False for identical reactions?

### ISSUE THREAD

**Issue by nickvandewiele** [GreenGroup/RMG-Py#356]
This commit 2990dcef5041fd3bb323290407fae480d1cc6254 shows that `rmgpy.Reaction.isIsomorph(reaction)` returns `False` when it is compared to a deep copy of itself.

My understanding is that this should return True even if the two reactions are different objects in memory.

**Comment by connie** [comment]
Are you sure this is the case?  It may be failing within the copy part of the code if you are using Species objects as reactants/products... I have tested it and gotten a True.

**Comment by nickvandewiele** [comment]
The behavior changes when I replace `deepcopy(rxn)` by `rxn.copy()`. I get this instead:

```
======================================================================
ERROR: Test that two Reactions objects can compared
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant_data/RMG-Py/rmgpy/reactionTest.py", line 496, in testReactionComparison
    self.assertTrue(rxn.isIsomorphic(rxn.copy()))
  File "rmgpy/reaction.py", line 1013, in rmgpy.reaction.Reaction.copy (build/pyrex/rmgpy/reaction.c:27231)
    def copy(self):
  File "rmgpy/reaction.py", line 1025, in rmgpy.reaction.Reaction.copy (build/pyrex/rmgpy/reaction.c:26926)
    other.reactants.append(reactant.copy(deep=True))
AttributeError: 'rmgpy.species.Species' object has no attribute 'copy'

----------------------------------------------------------------------
```

Which shows that `Reaction` expects its reactants and products to be a `Molecule` rather than a Species.

Maybe because we have never created a reaction object with Species objects except in `reactionTest` this never lead to trouble.

When the reactants and products attributes of a reaction are created, we could maybe check the whether they are Molecule's and not Species.

**Comment by rwest** [comment]
Could you add similar tests for Molecule and Species objects (unless they already exist) and do they also fail?

**Comment by nickvandewiele** [comment]
`isIsomorphic()` for `Molecule `and `rmgpy.species.Species `works fine. I am probably just witnessing how `deepcopy() `fails to do its job.

**Comment by rwest** [comment]
@pierrelb suspected something to do with connectivity values on atoms not being set correctly after a copy...?

**Comment by connie** [comment]
I believe that you can perform isomorphism checks between Reaction objects even when the reactants and products are Species objects - however it's the Reaction.copy() function that doesn't work with Species objects....  We tend to actually interchange between Molecule and Species objects with the Reaction class, so it's not a good thing that the Reaction.copy() only works on one type.

**Comment by nickvandewiele** [comment]
The problematic reaction isomorphism was because of the fact that the Species definition did not specify any Molecule. E.g.:

```python
        acetylperoxy = Species(
            label='acetylperoxy',
            thermo=Wilhoit(Cp0=(4.0*constants.R,"J/(mol*K)"), CpInf=(21.0*constants.R,"J/(mol*K)"), a0=-3.95, a1=9.26, a2=-15.6, a3=8.55, B=(500.0,"K"), H0=(-6.151e+04,"J/mol"), S0=(-790.2,"J/(mol*K)")),
        )
```

My apologies for the waste of your time (and mine).
