### ISSUE TITLE
Not drawing explicit hydrogens on things like formyl radical

### ISSUE THREAD

**Issue by rwest** [GreenGroup/RMG-Py#359]
The old website, running old RMG-Py (before the new adjacency list) drew this for formyl:

![screen shot 2015-03-25 at 5 48 43 pm](https://cloud.githubusercontent.com/assets/93807/6836308/47b96604-d317-11e4-8626-e700d77c3533.png)

The new website draws this:
![screen shot 2015-03-25 at 5 47 53 pm](https://cloud.githubusercontent.com/assets/93807/6836313/4f34290a-d317-11e4-98f2-bbfa7df5fea1.png)

The new one is misleading and confusing.
This *may* be a website bug, but I think it's an RMG-Py bug, because the URL for the image looks to contain the full correct adjacency list, it is just being drawn wrong.

**Comment by connie** [comment]
What commit is the old RMG-Py on?

**Comment by connie** [comment]
Fixed via https://github.com/GreenGroup/RMG-Py/commit/503cccbabb9b25465be149dedc10777638543e7c   

Was an error related to the exception made for CO molecule drawing.
