### ISSUE TITLE
adjacency list lines with simply a '*', rather than a '*1'?

### ISSUE THREAD

**Issue by nickvandewiele** [GreenGroup/RMG-Py#368]
While printing the adjacency lists of molecules during an RMG simulation I encountered formats like this:

```
CH3
multiplicity 2
1 * C u1 p0 c0 {2,S} {3,S} {4,S}
2   H u0 p0 c0 {1,S}
3   H u0 p0 c0 {1,S}
4   H u0 p0 c0 {1,S}

O2
multiplicity 3
1 * O u1 p2 c0 {2,S}
2   O u1 p2 c0 {1,S}

C2H5
multiplicity 2
1   C u0 p0 c0 {2,S} {3,S} {4,S} {5,S}
2 * C u1 p0 c0 {1,S} {6,S} {7,S}
3   H u0 p0 c0 {1,S}
4   H u0 p0 c0 {1,S}
5   H u0 p0 c0 {1,S}
6   H u0 p0 c0 {2,S}
7   H u0 p0 c0 {2,S}
```

So, the atom only has a `*` label, rather than a `*` followed by an integer.

Is this format allowed, or am I looking at a bug here?

**Comment by rwest** [comment]
Used in group matching for thermo. Eg. Look for the group centered on the starred atom.
(May also exist in some reaction family trees with self reverse?).

What were you in the middle of when you printed them? Estimating thermo? Looking for reactions?

**Comment by nickvandewiele** [comment]
I printed the adj lists of the reactants in `KineticsFamily.__generateReactions(...)`

Could you elaborate on :
>May also exist in some reaction family trees with self reverse?

So I am mistaken that atom labels related to kinetics should always carry an index following the star?

**Comment by rwest** [comment]
No, you may well be right. That was a half formed memory and I don't have easy access to check now. I seem to recall that some reaction family trees have something funny about them...

**Comment by rwest** [comment]
See group definitions in Radical recombination family. Only one tree to match `*1` and `*2` so groups labeled with just a `*`

**Comment by nickvandewiele** [comment]
Thanks for the pointers @rwest!


The recipe of the radical recombination family uses *labeled* stars:
```
recipe(actions=[
    ['FORM_BOND', '*1', 'S', '*2'],
    ['LOSE_RADICAL', '*1', '1'],
    ['LOSE_RADICAL', '*2', '1'],
])
```

Whereas the groups only use *unlabeled* stars, e.g.:
```
entry(
    index = 1,
    label = "Y_rad",
    group = 
"""
1 * R u1
""",
    kinetics = None,
)
```

So, since I have encountered reactants with atoms bearing *unlabeled* stars, it means the label from the matched group is transferred to the corresponding atom of the molecule:
```python

KineticsFamily.__generateProductStructures(...):

        # Tag atoms with labels
        for m in maps:
            for reactantAtom, templateAtom in m.iteritems():
                reactantAtom.label = templateAtom.label
```

And because the radical recombination family recipe uses \*1 and \*2 rather than \*, it needs an *ad hoc* solution for this, by converting \* to \*[index]
```python
KineticsFamily.applyRecipe(...):
        if label == 'r_recombination' and forward:
            identicalCenterCounter = 0
            for atom in reactantStructure.atoms:
                if atom.label == '*':
                    identicalCenterCounter += 1
                    atom.label = '*' + str(identicalCenterCounter)
            if identicalCenterCounter != 2:
                raise Exception('Unable to change labels from "*" to "*1" and "*2" for reaction family {0}.'.format(label))

```

I see the logic of encountering \* as atom labels outside thermo calculation. One could argue that using the same symbol for thermo groups as for kinetics groups could potentially lead to erroneous matching when the labels are not properly cleared. In fact, finding these \* atoms labels in reactants that had yet to undergo reactions seems to be an indication that these atom labels are not always cleared when they should be.

However, I currently don't see why converting \* to \*[index] could not be done more upstream, right when the \* labels are being assigned to the atoms.

**Comment by nickvandewiele** [comment]
After some more careful study, I understand why moving the conversion of  \* to \*[index] in reactants is not done more upstream right when the \* labels are being assigned to the atoms.

1) **Reactant Groups of a kinetics tree do not exist as separate objects**
For bimolecular reaction families with 2 identical reactant templates, e.g. Yrad, the reactant tree is only stored once in memory and referenced twice rather than copied for each reactant.

If you don't make a copy of the reactant `Group` prior to converting \* to \*[index] then you are modifying the same object in memory. After the first loop the \* to \*1, in the second loop, \* won't exist anymore, and hence `atom.label == '*'` won't be matched anymore. Therefore, a deep copy is made of the Group that is used for both reactants to ensure that two separate objects can be manipulated:
```python
        for s in reactantStructures:
            reactantStructure = reactantStructure.merge(s.copy(deep=True))
```

2) **The original reactant molecules should keep on using \* rather than \*1 to match kinetics tree nodes**
In the original design, the \* of reactant atoms is converted into \*[index] in the reactant molecules that were used to generate product structures. Searching the most specific node in the kinetics tree uses the \* label rather than the \*[index] label. Therefore, you would need to convert and revert the atom labels if you want to do that operation outside the `applyRecipe` method. That's double work.

**Comment by rwest** [comment]
Feel free to add some comments to the source code to save other people from re-doing this analysis...
(you could also include a link to this issue)
