### ISSUE TITLE
getReactionTemplate() does not descend union groups correctly

### ISSUE THREAD

**Issue by connie** [GreenGroup/RMG-Py#381]
From an error found in Max's ditertbutylsulfide job, we find that in the intra_substitutionS_cyclization family, there is a unknown kinetics error.  

`
rmgpy.data.kinetics.common.UndeterminableKineticsError: (Reaction(reactants=[Molecule(SMILES="[CH2]C(C)(C)SC(C)(C)C")], products=[Molecule(SMILES="CC1(C)CS1"), Molecule(SMILES="C[C](C)C")], pairs=[[Molecule(SMILES="[CH2]C(C)(C)SC(C)(C)C"), Molecule(SMILES="CC1(C)CS1")], [Molecule(SMILES="[CH2]C(C)(C)SC(C)(C)C"), Molecule(SMILES="C[C](C)C")]]), 'Kinetics could not be determined. Unable to find matching template for reaction <Molecule "[CH2]C(C)(C)SC(C)(C)C"> <=> <Molecule "CC1(C)CS1"> + <Molecule "C[C](C)C"> in reaction family <KineticsGroups "intra_substitutionS_cyclization/groups">.Trying to match [<Entry index=1 label="XSYJ">, <Entry index=2 label="YJ">, <Entry index=3 label="S-RR">] but matched [<Entry index=5 label="XSR3J_S">, <Entry index=157 label="S-Cs(CsCsCs)C">]')
`

The source of the error is from the function getReactionTemplate in rmgpy/data/groups.py
The function descends into the first union child of the kinetics group and obtains an atomList from it.  It preemptively checks that all labeled atoms in that group exist in the reactant.  However in our case, out that the group ``YJ`` is a union group, and the children actually do not contain the same labeled atoms.. thus, even though the reactant can match one of the children, this bug makes it so that it believes the labeled atoms don't exist.

Two ways to fix: check all children's labeled atoms OR make databaseTest to ensure that all children of union groups contain the same labeled atoms..

**Comment by rwest** [comment]
if this is a bug in the database, I'd vote for option two: improve our databaseTest and fix the bug there.
However, if at least one of the children contains the required labeled atom, then it sounds like the union should also contain that labeled atom and pass the pre-emptive test.

**Comment by connie** [comment]
I'm leaning towards fixing the code, and not the database, because OR groups should be flexible enough to have children with different labeled atoms.

Maybe instead of performing this check, skip it only for OR groups... it'll probably only add a little bit of time because there aren't so many OR groups to begin with, and the descendTree function should quickly isolate which path to go down.

**Comment by rwest** [comment]
I guess it should only enforce the species contains labelled atoms when ALL the children of the union contain those labeled atoms.
