### ISSUE TITLE
intra_substitutionCS_isomerization not working

### ISSUE THREAD

**Issue by connie** [GreenGroup/RMG-Py#382]
This family template uses the reversible reaction template XSYJ -> XSYJ

However, the head node requires a reactant that fits a group such as this XSR3J:

    1 *3 R!H u1 {2,[S,D]}
    2 *2 Ss  u0 {1,[S,D]} {3,S}
    3 *1 C   u0 {2,S}

And the reaction recipe states 

    recipe(actions=[
    ['BREAK_BOND', '*1', 'S', '*2'],
    ['FORM_BOND', '*1', 'S', '*3'],
    ['GAIN_RADICAL', '*2', '1'],
    ['LOSE_RADICAL', '*3', '1'],
    ])

We see that the Sulfur atom gains a radical, and the R!H group loses a radical in the process.  When we then try to reverse this template, it no longer works because the Sulfur now contains a radical and is no longer isomorphic to the XSYJ group.  So does this mean that this family is not reversible?

Some investigation shows that in RMG-Java using the PopulateReactions module the reaction only shows up when the reactant is present in the forward direction, but not when the product is present.  This also shows that the template is not reversible as is.  Maybe all we need is to write in a reverse template?

**Comment by rwest** [comment]
Yes, it looks to me like it is not its own reverse; the product cannot match the reacting template, and It should be something like XSYJ -> XYSJ.

Can our database tests be made to catch this type of error?

**Comment by connie** [comment]
It's pretty bad how we only detect this type of error when the appropriate reactants that work for the family are put in an input file...  at least Py is throwing an error, whereas Java pretty much stealth hides it.

i.e.

    1 C 0 {6,S}
    2 C 0 {6,S}
    3 C 0 {6,S}
    4 C 0 {7,S}
    5 C 0 {7,S}
    6 C 0 {1,S} {2,S} {3,S} {8,S}
    7 C 0 {4,S} {5,S} {8,S} {9,S}
    8 S 0 {6,S} {7,S}
    9 C 1 {7,S}

**Comment by rwest** [comment]
This problem is fixed by https://github.com/GreenGroup/RMG-database/pull/64, but before closing this issue, could we add something to `RMG-Py/databaseTest.py` to prevent it reoccurring undetected?

**Comment by rwest** [comment]
It was closed automatically by github when I pushed the commit to RMG-database. I'm reopening until unit test added.
