### ISSUE TITLE
Unmarked duplicate reactions from different families in chemkin file

### ISSUE THREAD

**Issue by pierrelb** [GreenGroup/RMG-Py#64]
The reaction `C1C(=CC=C1)[CH2](24) <=> [C@@H]12CC(=C2)C[CH]1(1261)`
is created from  Template reaction: Intra_R_Add_Exocyclic [R5_SD_D,doublebond_intra_HNd_pri,radadd_intra_cs2H]  and Template reaction: Intra_R_Add_Endocyclic [R5_SS_D,doublebond_intra_pri_HDe,radadd_intra_cs2H]. Both appear in the chemkin file, but without a DUPLICATE tag, making it invalid

**Comment by connie** [comment]
This error has been fixed.
