### ISSUE TITLE
mention GraphViz and mencoder in general requirements

### ISSUE THREAD

**Issue by nickvandewiele** [GreenGroup/RMG-Py#79]
both libraries are required if you want to run generateFluxDiagram module. The former for the graph layout, the latter for the stitching of the flux diagram snapshots into a movie.

Since they are not python related they should be mentioned somewhere else than requirements.txt i think.

**Comment by connie** [comment]
Closed via https://github.com/GreenGroup/RMG-Py/commit/8f464b54e9516e5a527e8aeac4485abac6ca6371
